### ISSUE TITLE
LIB: Creació component horitzontal d'autenticació LoginIB 

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/LOGINIB#1]
- Creació del component horitzontal d'autenticació CAIB que integrarà d'inici l'autenticació per Cl@ve 2.0 i anònima.
- Definició del plugin d'integració

**Comment by sgelabert-dgtic** [comment]
En relació amb el comentari https://github.com/GovernIB/sistra2/issues/31#issuecomment-408805958, indicau aquí els problemes que han sorgit i si heu rebut o no resposta del CAID

**Comment by rsanz-indra** [comment]
Respuesta del CAID:
`Buenos días, Les informamos de que Cl@ve 1.0 y 2.0 son entornos separados, y por tanto, es necesario el alta en Cl@ve 2.0 para poder hacer uso de dicho entorno. El servicio de Cl@ve 2.0 ya está disponible para poder tramitar el alta, por lo que rogamos hagan uso del formulario disponible en el PAE http://administracionelectronica.gob.es/ctt/clave para solicitar el alta en Cl@ve 2.0 en una nueva incidencia. Si una vez les confirmen el alta, siguen teniendo problemas, rogamos nos sea indicado`

CAIB solicita alta para Cl@ve 2.0
