### ISSUE TITLE
LIB: Canvis relatius a l'adaptació de contextos i securització

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/LOGINIB#10]

**Comment by rsanz-indra** [comment]
Se ha modificado el empaquetamiento de los EARs para adaptar a la configuración indicada por Serveis Web, pero deberemos revisar la solución que hemos implementado ya que nos ha dejado de funcionar el despliegue de la aplicación a través del plugin de JBoss que usamos en los entornos locales de desarrollo.
