### ISSUE TITLE
 LIB: redimensionar al 90% el logo del Govern

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/LOGINIB#14]

**Comment by dmadronal-indra** [comment]
Buenas, hemos revisado los css necesarios para mostrar el logo correctamente. 
para visualizar los cambios en proves es necesario incluir la siguiente linea en el properties como valor de la propiedad **personalizacion.A04003003.css**:

 `.imc-cabecera h1 img{  height: auto; width: 10em; } .imc-contingut{background-color: #eaeaea; top: calc(50% - 5.8em);} .imc-cabecera { font-size: 1.2em; } @media only screen and (max-width : 1024px) {.imc-cabecera { font-size: 1em; } .imc-contingut{top: calc(50% - 7em);} } @media only screen and (max-width : 670px) {	.imc-cabecera { font-size: .6em; } .imc-cabecera h1 img{ margin-top: 1em;} .imc-contenidor { margin-top: 2em; }}`
