### ISSUE TITLE
L'API REST de comunicació amb LOGINIB només funciona amb SpringWeb

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/LOGINIB#15]
L'API REST de comunicació amb LOGINIB només funciona amb SpringWeb. L'he intentada fer funcionar amb altres clients rest y no funciona. S'hauria de fer que fos independents del client REST que utilitzis.

**Comment by rsanz-indra** [comment]
Puedes indicarnos en que punto exactamente te has encontrado el problema para poder investigarlo?
Las pruebas unitarias las hacemos desde la consola swagger, que es un cliente REST independiente, y no hemos detectado nada raro.
