### ISSUE TITLE
LIB:  Avaluar la conveniència de modificar LOGINIB per a que ens proporcioni totes les dades del certificat

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/LOGINIB#16]
Certificat de representant: que detecti els de tipus 11-12 i després a SISTRA2, triar el representant a l'autenticació.

**Comment by rsanz-indra** [comment]
LOGINIB ya realiza esta detección: detecta los de tipo 11 y 12 y devuelve la información de la empresa y representante.
