### ISSUE TITLE
LIB: Maquetació de la pàgina de login

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/LOGINIB#2]
Maquetació de la pàgina de login per accés a Cl@ave i autenticació anònima

**Comment by jsastre-dgtic** [comment]
![image](https://user-images.githubusercontent.com/18436867/46729730-7840d980-cc86-11e8-841d-b91719f1dd0f.png)
![image](https://user-images.githubusercontent.com/18436867/46729754-855dc880-cc86-11e8-97c2-61fb943bbfe5.png)
