### ISSUE TITLE
LOGINIB Desglossar Llinatges

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/LOGINIB#20]
En cas de _detectar que els llinatges no estan desglossats_ **(*)**, es mostrarà a l'usuari una pantalla perquè confirmi el desglossament.

Es pot proposar el desglossament automàticament, però l'usuari ha de ser qui confirmi que és correcte. En qualsevol cas, el contingut concatenat dels cognoms desglossats ha de coincidir exactament amb els cognoms sense desglossar.

Per evitar que cada vegada l'usuari hagi de fer el desglossament de cognoms, s'emmagatzemarà aquest desglossament (nif, llinatges sense desglossar, llinatge1, llinatge2) en una taula de LOGINIB i en cas que s'autentiqui de nou es verificarà si s'ha realitzat prèviament el desglossament (recerca per nif i cognoms sense desglossar).

La pantalla per dur a terme el desglossament de cognoms haurà de ser personalitzada per entitat mitjançant les propietats de personalització existents al properties de LOGINIB.

**(*)** Cal explicar com es detecta i incloure la possibilitat d'editar el camp nom (name)

**Comment by jcerdar-indra** [comment]
Se soluciona en el tag 2.4.0_0 (091e71a)

**Comment by jcerdar-indra** [comment]
Como se indica en el documento de estimación, se han implementado las siguientes funcionalidades: 

**Mostrar pantalla de edición de datos al acceder**
Al acceder por primera vez, aparecerá la pantalla de desglose. Esto se puede probar por ejemplo iniciando un trámite desde SISTRAMIT: 
![#20DesgloSTTPF](https://user-images.githubusercontent.com/96287364/160094772-a44e8275-a363-4e38-8279-ac7892892481.gif)

**Forzar mostrar pantalla de edición de datos**
Para que un usuario pueda modificar estos datos, se añade un parámetro en la llamada de loginIB que permite forzar que se muestre y edite la información almacenada. Esto puede ser útil para implementar el acceso desde aplicaciones externas, p.e. Carpeta. 

Para probarlo, se puede acceder al webservice de loginIB: <dominio>/loginibws/rest/swagger-ui.html

Allí, hacer un POST a /login. Un ejemplo de datos para el post es el siguiente, en la que es añade el parámetro para forzar el desglose: 
{
  "aplicacion": "SISTRA2",
  "auditar": false,
  "entidad": " A04003003",
  "forzarAutenticacion": false,
  "idioma": "ES",
  "inicioClaveAutomatico": false,
  "metodosAutenticacion": "CLAVE_CERTIFICADO",
  "paramsApp": {
    **"parametros": [
      {
        "propiedad": "forzarDesglose",
        "valor": "S"
      }**
    ]
  },
  "qaa": 1,
  "urlCallback": "http://www.google.es/",
  "urlCallbackError": "http://www.google.es/"
}

Luego copiar la URL que devuelve la función y ver que redirige a la pantalla de forzareDesglose. 

![image](https://user-images.githubusercontent.com/96287364/160095533-1dfff933-3704-47dc-b4a6-d6a3918475e6.png)

**Establecer propiedad para permitir deshabilitar la gestión del desglose**
Esta propiedad se añade a nivel de properties, en el archivo loginib.properties y es la siguiente: 
desglose.omitirDesglose=false

Por defecto está a false para permitir habilitar el desglose. 

**Crear url de soporte para mostrar información retornada por el método de autenticación**
La URL de soporte que muestra la información de los datos es la siguiente: <URL dominio>/loginibfront/test.html
![image](https://user-images.githubusercontent.com/96287364/160096078-91ac7ac9-a6d0-42a6-b33c-8b16245e1092.png)

**Comment by jcerdar-indra** [comment]
**Creación de un Backoffice de administración**

Este Backoffice es accesible mediante la siguiente URL: <dominio>/loginibback/

Para poder acceder, el usuario que accede necesita tener el rol LIB_BACK. 

Permite consultar certificados desglosados y modificarlos desde allí: 
![image](https://user-images.githubusercontent.com/96287364/160100045-cb8f50a5-34c2-4953-8be3-071c95429888.png)
![image](https://user-images.githubusercontent.com/96287364/160100060-62b90e62-3f73-4a3a-b6da-06d4c7250d24.png)

**Comment by avillen-dgtic** [comment]
👍
