### ISSUE TITLE
Nou Joc d'integració amb Cl@ve2

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/LOGINIB#21]
https://administracionelectronica.gob.es/pae_Home/pae_Actualidad/pae_Noticias/Anio2021/Octubre/Noticia-CTT-2021-10-04-Nuevo-Kit-de-integracion-con-Clave2.html?idioma=ca
Avaluar i fer el canvi.

**Comment by jcerdar-indra** [comment]
Se soluciona en el tag 2.4.0_0 (https://github.com/GovernIB/LOGINIB/commit/091e71a1ff1379af0ba63ee2a80c0f0479e57c73)

**Comment by avillen-dgtic** [comment]
👍
