### ISSUE TITLE
Error al mostrar la icona

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/LOGINIB#24]
Aquesta imatge no està ben dimensionada.
![image](https://user-images.githubusercontent.com/83401259/163153643-4b58fc11-8705-4391-ab5f-0c865592d596.png)

**Comment by avillen-dgtic** [comment]
![image](https://user-images.githubusercontent.com/83401259/171377495-c6a3ad5a-dbb3-40f4-ad0c-5a5e60a40325.png)

**Comment by jsastre-dgtic** [comment]
![imatge](https://user-images.githubusercontent.com/18436867/182790244-5a7a9b91-73d4-4b62-a033-0b89b0acd06d.png)
