### ISSUE TITLE
Icona amb mides petites

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/LOGINIB#25]
![image](https://user-images.githubusercontent.com/83401259/165911188-6c94b081-a75e-4b44-9720-70ffadc96272.png)

Això a la versió 2.4.0_0

**Comment by avillen-dgtic** [comment]
![image](https://user-images.githubusercontent.com/83401259/165929071-8cdebcd6-1723-4143-a4cf-6621c10ba56d.png)

Això a la versió 2.4.0_1

**Comment by jsastre-dgtic** [comment]
![imatge](https://user-images.githubusercontent.com/18436867/182790336-8332a795-48c7-4b51-baa0-ed7e7666dfaf.png)
