### ISSUE TITLE
Logo Plataforma

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/LOGINIB#26]
El mateix passa a LIB.
Cal resoldre aquesta presentació. Hem d'alinear els elements comuns
https://github.com/GovernIB/paymentib/issues/11

**Comment by jsastre-dgtic** [comment]
Surt un logo "romput"

![imatge](https://user-images.githubusercontent.com/18436867/182788586-f7d97c80-2c62-4acc-af96-f832f2afd4e7.png)

A l'esborrar un usuari surt una "doble pantalla" de confirmació:
![lib_finestres](https://user-images.githubusercontent.com/18436867/182788678-2718b16d-9e49-4f6b-8123-bb9ad51a1370.gif)

**Comment by jcerdar-indra** [comment]
Se resuelve en el TAG 2.4.1_1 (5f3f24e)

**Comment by jcerdar-indra** [comment]
Se elimina error en el logo y ya no aparece doble confirmación: 
![#26](https://user-images.githubusercontent.com/96287364/184156649-17d24165-64f0-4094-a5bd-439e6468af60.gif)

**Comment by avillen-dgtic** [comment]
👍
