### ISSUE TITLE
Ordre dels llinatges

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/LOGINIB#28]
L'ordre dels llinatges no es reflecteixen quan es fa el canvi amb el backoffice.

**Comment by avillen-dgtic** [comment]
#20

**Comment by jsastre-dgtic** [comment]
![imatge](https://user-images.githubusercontent.com/18436867/182792855-e66ceedd-1e29-4c7d-8de3-a295d6e763e4.png)
