### ISSUE TITLE
Canviar la pantalla de test perquè mostri info QAA

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/LOGINIB#29]
Cal mostrar tant el QAA que s'envia a LoginIB com el QAA que retorna Cl@ve en realitzar l'autenticació.

**Comment by jsastre-dgtic** [comment]
1.- https://www.caib.es/loginibfront/test.html 
No es reflecteix el QAA correctament, sempre surt 1

2.- Per defecte hauria d'estar en català i es presenta en castellà tot i tenir el navegador en català.

3.- La info del nivell QAA hauria de sortir com a Carpeta, no només a la pantalla de test de LIB
![imatge](https://user-images.githubusercontent.com/18436867/182775064-bfbc6e5f-926b-47ee-976a-910dc5f3b93e.png)

**Comment by jcerdar-indra** [comment]
Se resuelve en el TAG 2.4.1_1 (5f3f24e).

**Comment by jcerdar-indra** [comment]
1.- Se ha añadido el QAA que retorna Cl@ve en función del método de autenticación: 
![image](https://user-images.githubusercontent.com/96287364/184155292-2877febd-04d0-4242-bc79-ed49b8ded52c.png)

También se ha configurado la llamada a esta URL para que pueda pasarse el parámetro qaa, y así poder enviar distintos niveles de QAA hacia Cl@ve. Ejemplo: 
https://dev.caib.es/loginibfront/test.html?qaa=2

2.- Se pone el idioma por defecto en catalán. 

3.- Entendemos que el punto 3 hace referencia a la visualización de esta información en el asistente de tramitación (SISTRAMIT). En caso de ser así, ¿podríamos cerrar esta issue y revisar el punto 3 para SISTRA2?

**Comment by jparedes-indra** [comment]
Se muestra el QAA devuelto por Cl@ve en el asistente de tramitación.

![imagen](https://github.com/GovernIB/LOGINIB/assets/67064375/817df3a8-9702-4440-ad02-9dcc1a1356db)

**Comment by avillen-dgtic** [comment]
Amb DNIe surt qaa baix

![image](https://github.com/GovernIB/LOGINIB/assets/83401259/646d7cb8-6e15-4661-9a8d-792c7af8866c)

**Comment by avillen-dgtic** [comment]
Clave permanente
![image](https://github.com/GovernIB/LOGINIB/assets/83401259/d3d36a90-554a-457b-8859-ecc9af49452c)

**Comment by avillen-dgtic** [comment]
👍
