### ISSUE TITLE
Normalitzar els NIFs

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/LOGINIB#33]

**Comment by jsastre-dgtic** [comment]
Actualment, tenim DNIe que es parsegen amb el dígit de control en minúscula, cosa que RW3 no admet i surt el missatge "Tipus d'identificació no controlat". Per tal d'evitar aquest problema, cal modificar LIB perquè sempre tracti amb majúscules les autenticacions amb certificat.

**Comment by jparedes-indra** [comment]
Se resuelve en TAG loginib-2.4.2_0 (8f807c4).

Ahora, al autenticarse con un certificado con un NIF con letra en minúscula, se normaliza ese formato para ponerla en mayúscula antes de acceder al asistente de tramitación.
