### ISSUE TITLE
Incloure el menú contextual a LIB_BACK

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/LOGINIB#34]
![image](https://github.com/GovernIB/LOGINIB/assets/18436867/364d1366-3523-4443-91cb-fbe8844cf67a)

**Comment by jparedes-indra** [comment]
Se incluye el menú contextual.

![imagen](https://github.com/GovernIB/LOGINIB/assets/67064375/bc302f47-a7f7-460f-847f-fee3988a1dfa)

**Comment by avillen-dgtic** [comment]
👍
