### ISSUE TITLE
No es contempla que els estrangers poden tenir un sol llinatge

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/LOGINIB#35]
No es contempla que els estrangers poden tenir un sol llinatge

![image](https://github.com/GovernIB/sistra2/assets/18436867/ce3f65eb-e617-40a0-8093-e6ae717cdcfc)

**Comment by jparedes-indra** [comment]
Se permite guardar un desglose de apellidos sin segundo apellido, al dejar de ser obligatorio.

![imagen](https://github.com/GovernIB/LOGINIB/assets/67064375/ee5917c0-6c32-445e-8798-6364b38fb502)

**Comment by avillen-dgtic** [comment]
👍
