### ISSUE TITLE
Incloure gestió nou IDP de cl@ve

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/LOGINIB#37]
Gestió del nou IdP anomenat “Cl@ve Movil” per simplificar i unir l'experiència dels actuals “Cl@ve Pin” i “Cl@ve Permanente”.

Ara el que ens arriba si no es capa aquesta opció és “PIN24H_MOVIL” i aquest nou IDP no està contemplat ni per LIB ni per SISTRA2 per tant no funcionarà.
Els IDP's suportats actualment són:
- AFIRMA (clau certificat)
- PIN24H (clau pin)
- SEGSOC (clau permanent)

**Comment by jparedes-indra** [comment]
Se muestra el nuevo IdP ofrecido por Cl@ve y se accede y gestiona apropiadamente durante el proceso de tramitación.

![imagen](https://github.com/GovernIB/LOGINIB/assets/67064375/f00b32af-9924-41e5-bf5a-608e5b311e98)

![imagen](https://github.com/GovernIB/LOGINIB/assets/67064375/251ab960-5f52-42c9-8a74-61d2629355b2)

**Comment by avillen-dgtic** [comment]
👍
