### ISSUE TITLE
Actualització versió de Primefaces

### ISSUE THREAD

**Issue by dmadronal-indra** [GovernIB/LOGINIB#39]
Actualització versió de Primefaces a la darrera versió

**Comment by jsastre-dgtic** [comment]
Parlam de la 13?
Veure: https://github.com/GovernIB/sistra2/issues/747

**Comment by dmadronal-indra** [comment]
la actualización de primefaces se realizará a la ultima versión, actualmente la v14

**Comment by jparedes-indra** [comment]
Se actualiza la versión de PrimeFaces a la 14, como muestra el pom.xml del proyecto.

![image](https://github.com/user-attachments/assets/817bd11b-002d-400e-9fd4-89719d408832)

**Comment by avillen-dgtic** [comment]
👍🏼
