### ISSUE TITLE
Eliminar propietat "anonimo.inicioAuto"

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/LOGINIB#40]
A les properties de LIB de la instal·lació del Govern, deixar només la propietat "acceso.auto" i eliminar "anonimo.inicioAuto", si no ha de tenir cap conseqüència "inesperada".

**Comment by jparedes-indra** [comment]
Se prueba que LIB funciona correctamente tras eliminar o comentar esta propiedad, que ya no es necesaria en la CAIB

![image](https://github.com/user-attachments/assets/d9cc5733-396c-4ec0-b1a9-a4336d19246e)

**Comment by jparedes-indra** [comment]
Se prueba que LIB funciona correctamente tras eliminar o comentar esta propiedad.

![image](https://github.com/user-attachments/assets/d9cc5733-396c-4ec0-b1a9-a4336d19246e)

**Comment by avillen-dgtic** [comment]
👍🏼
