### ISSUE TITLE
No se pot modificar des de LIBBack quan el nom és compost

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/LOGINIB#42]
Intentant canviar 2on llinatge surt:

![image](https://github.com/user-attachments/assets/b7392cf3-6720-4378-a377-bb060b1127b9)

**Comment by jparedes-indra** [comment]
Se pueden guardar nombres con espacio.

![image](https://github.com/user-attachments/assets/f4163edd-cd30-44e1-8f9a-f02648c59713)
![image](https://github.com/user-attachments/assets/49ddf3ea-3955-43ce-8e63-4d74f629559c)

**Comment by avillen-dgtic** [comment]
👍🏼
