### ISSUE TITLE
LIB: ampliació de dades de sessió a poder gestionar en els tràmits, mitjançant la recollida d'informació addicional de la resposta de Cl@ve

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/LOGINIB#8]
Aquest punt passa per ampliar els camps disponibles al tiket de l'api/rest de loginib.

A la documentació de cl@ve1, tenim:

Aparte de los atributos heredados de STORK 2.0, el sistema ha incluido los siguientes que se
describen a continuación:
 isdnie, que permitirá conocer si la identificación se ha realizado con un DNI Electrónico
(DNIe).
 allowLegalPerson, que habilitará la posibilidad al usuario de autenticarse empleando
un certificado de persona jurídica. Este atributo se envía como parámetro vía HTTPPOST,
de la misma forma que es enviado el atributo idplist.
 isLegalPerson, que permitirá conocer si la identificación se ha realizado empleando un
certificado de persona jurídica. Este atributo únicamente estará disponible si el
proveedor de servicio ha permitido este tipo de certificado mediante
allowLegalPerson. Este atributo se recibe como respuesta vía HTTP-POST.

https://administracionelectronica.gob.es/ctt/resources/Soluciones/766/Descargas/Documento%20de%20integracion%20para%20SP%201-1-.pdf?idIniciativa=766&idElemento=2746

**Comment by rsanz-indra** [comment]
Respecto a las propiedades indicadas:
- allowLegalPerson / isLegalPerson: actualmente ya se pasa el parámetro a Cl@ve1 para permitir autenticarse con certificados de persona jurídica (clasificación = 1, a extinguirse) y nuevos certificados EIDAS de representación (clasificación = 11 y 12). No se usa isLegalPerson ya que directamente se interpretan los datos de @firma para extraer la clasificación del certificado y los datos del representante y representado. En la documentación de Cl@ve2 no aparecen estas propiedades.
- isdnie: no se está tratando automáticamente este dato, pero hay que tener en cuenta que no aparece en la documentación de Cl@ve2

Según lo anterior, lo que tendría más sentido es añadir la clasificación del certificado a los datos de respuesta de LoginIB para una autenticación con certificado

**Comment by jsastre-dgtic** [comment]
https://administracionelectronica.gob.es/dam/jcr:c0c76b68-daa8-469f-8885-164357d78815/Preguntas_frecuentes_Reglamento_eIDAS.pdf

3.11 ¿Qué atributos se pueden obtener a través del nodo eIDAS?
Para personas físicas:
• Datos obligatorios
– Identificador de unicidad (no persistente en todos los países)
– Nombre
– Apellido
– Fecha de nacimiento
Para personas jurídicas:
• Datos obligatorios
– Identificador de unicidad
– Nombre legal

Bastaria mirar el camp de la data de naixement per a distingir-ho?
