### ISSUE TITLE
Dudas acerca de autenticación en servidor de aplicaciones

### ISSUE THREAD

**Issue by perelengo** [GovernIB/LOGINIB#9]
Buenos días,
tengo la siguiente duda respecto al módulo LoginIB y su uso por parte de terceras aplicaciones:

-Por lo que entiendo, las aplicaciones no tienen que instalar LoginIB, sinó utilizar sus servicios. Cada aplicación debe tener un usuario y contraseña con el rol LIB_API, para llamar a los servicios de LoginIB. 

-Si tuviéramos una aplicación en Jboss5 con front protegido por FORM cuya url fuera http://xxx.caib.es/miaplicacion-front/pagina, deberíamos editar la página de login (su URL actual seria http://xxx.caib.es/miaplicacion-front/pagina/j_security_check ) para que en este jsp haga una petición (autenticándose con el usuario-aplicación que tenga el rol LIB_API)  a http://xxx.caib.es/loginib/login con los parámetros urlCallbackLogin y urlCallbackError. Recibirá en la respuesta la URL de LoginIb donde debe redirigir al usuario para que seleccione el método de autenticación. El usuario autenticará y se retornará a la URL pasada en el parámetro inicial urlCallbackLogin. En esta página, se debe invocar al servicio http://xxx.caib.es/loginib/ticket/{ticket} y se recuperan los datos de autenticación del usuario. OK

Lo que no entiendo es la coletilla del paso 7 (se procede con la autenticación y se valida el usuario en la aplicación origen) y el paso 8 del diagrama de funcionamiento del manual de integración.

¿Se supone que la urlCallbackLogin  ya tenemos la cookie de auntenticación y ya estamos autenticados en el contexto JAAS?

Viendo el código de loginIB, no veo en ningún lado que se haga autenticación JAAS, ni tampoco que el tiquet de respuesta devuelva algo (contraseña, token encriptado,....) con lo que poder hacer login contra el mecanismo j_security_check del form, o del BASIC.   Quizá no me queda claro cuál de los campos hay que utilizar posteriormente, y quizá sea el punto clave para entender todo esto.

Por otro lado, no le veo sentido al método http://xxx.caib.es/loginib/ticket/{ticket} 
ya que sólo devuelve información del usuario, pero si no se consume, no veo que afecte en ningún momento al funcionamiento, sólo que lo invalida.

Gracias por vuestra atención.
Atentamente,
Pere Joseph Rodríguez

**Comment by anadal-fundaciobit** [comment]
Bones Pere:
    Perdona, però els ISSUES estan pensats com a Tiquets d'incidències i no com un "foro" o email de consultes. Contacta amb la DGTIC i demana qui és el responsable de PluginsIB_LOGINIB i redirecciona les teves dubtes cap a la persona o entitat que et comentin.

                              gràcies,

**Comment by perelengo** [comment]
Ok, perfecte.
Gracis.
